[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
solc_version = "0.8.20"
optimizer_runs = 800
via_ir = true
ffi = true
